### ISSUE TITLE
React Ideogram does not redraw organism when changed

### ISSUE THREAD

**Issue by matthewchan15** [eweitz/ideogram#104]
The issue is that the Ideogram doesn't redraw the organism, when the `organism` parameter is changed in both `React` and `vanilla` java script. For example if the `organism` is `'human'` and is changed to `'mouse`', it will still show the Ideogram graph of `'human'` still. I've been messing around with the Ideogram a lot trying to get this feature to work within react. It seems that other parameters changes can render a redraw of the graph such as `showBandLabels` and `orientation`. 

I have provided a test case for you to use to better understand the problem, which can be found here: https://github.com/matthewchan15/ideo-test-case

![ideo-display](https://user-images.githubusercontent.com/33464965/44731719-13983980-aaa1-11e8-8bad-8afe6f9d92d1.gif)

**Comment by eweitz** [comment]
This is fixed in `master` by https://github.com/eweitz/ideogram/commit/6cc82af5bf07cb396c9768ff63d822df6eb004fa.
