### ISSUE TITLE
Missing props in Ideogram API docs

### ISSUE THREAD

**Issue by matthewchan15** [eweitz/ideogram#106]
I've been trying to integrate all the props listed in the API [here](https://github.com/eweitz/ideogram/blob/master/api.md), into react. In order to test the props I've been using the example code found [here](https://eweitz.github.io/ideogram/). I've noticed a discrepancy where many of the props used in the example docs, are not listed in the API docs. 

For example in [homology](view-source:https://eweitz.github.io/ideogram/homology-basic), the prop **_perspective_** is not listed in the API docs. This is just one case. I find this to be very confusing, are these props no longer being used, or have they simply just been forgotten to be put in the API docs?

```

   var config = {
   organism: 'human',
   chromosomes: ['X', 'Y'],
   chrHeight: 400,
   chrMargin: 200,
   showBandLabels: true,
   perspective: 'comparative',
   rotatable: false,
   onLoad: onIdeogramLoad
   };

```

**Comment by eweitz** [comment]
@matthewchan15, good catch!  (And apologies for the delayed reply.)  I'll fix this as part of the upcoming release.

If you can list any other Ideogram configuration options that are missing from the API documentation, that would help.

**Comment by matthewchan15** [comment]
Sounds good, I'll update this issue with the missing properties, when I'm free.

**Comment by matthewchan15** [comment]
Hey again, here are the following props I found to be missing:
* Ancestors
* AnnotationTracks
* fullChromosomeLabels
* perspective
* ploidyDesc
* rangeSet
* filterable

**Comment by eweitz** [comment]
Thank you, Matthew!  I'll follow up here when this is fixed.

**Comment by eweitz** [comment]
Fixed:

* [ancestors](https://github.com/eweitz/ideogram/blob/master/api.md#ancestors)
* [annotationTracks](https://github.com/eweitz/ideogram/blob/master/api.md#annotationtracks)
* [fullChromosomeLabels](https://github.com/eweitz/ideogram/blob/master/api.md#fullchromosomelabels)
* [perspective](https://github.com/eweitz/ideogram/blob/master/api.md#perspective)
* [ploidyDesc](https://github.com/eweitz/ideogram/blob/master/api.md#ploidydesc)
* [rangeSet](https://github.com/eweitz/ideogram/blob/master/api.md#rangeset)
* [filterable](https://github.com/eweitz/ideogram/blob/master/api.md#filterable)
