### ISSUE TITLE
Question: Is it possible to load data locally into the Ideogram?

### ISSUE THREAD

**Issue by matthewchan15** [eweitz/ideogram#108]
I'm looking to load data locally into the Ideogram, for example if I wanted to load one of these files without using `dataDir`: https://github.com/eweitz/ideogram/tree/master/data/bands/ncbi

**Comment by eweitz** [comment]
Yes, you can load data locally by providing a relative URL to [`dataDir`](https://github.com/eweitz/ideogram/blob/master/api.md#datadir) or [`annotationsPath`](https://github.com/eweitz/ideogram/blob/master/api.md#annotationspath).  

The `dataDir` option handles band data. The `annotationsPath` option handles annotation data.  You can also define annotation data at runtime using the [`annotations`](https://github.com/eweitz/ideogram/blob/master/api.md#annotations) option.  Examples are referenced in the linked documentation.
