### ISSUE TITLE
Rotation animation for Ploidy and multiple Ploidy rendering issues 

### ISSUE THREAD

**Issue by matthewchan15** [eweitz/ideogram#110]
I noticed an issue on rotation where the chromosome labels of the Ideogram over lap -> https://eweitz.github.io/ideogram/ploidy-basic

When rotating multiple Ploidy ideograms, there seems to be a glitch with displaying it. -> https://eweitz.github.io/ideogram/ploidy-rearrangements

**Comment by eweitz** [comment]
Yes, this has always been an issue.  Thanks for reporting it.  I'll disable rotation in those particular examples.

If app developers have a particular use case for rotating polyploid ideograms, then that would help motivate this enhancement.
