### ISSUE TITLE
Annotation tooltips become displaced when user scrolls down 

### ISSUE THREAD

**Issue by matthewchan15** [eweitz/ideogram#115]
Hi, I am using the latest master, and have noticed an issue with the annotations. It seems that when the user scrolls down, and hovers over an annotation, the annotation becomes displaced upwards. I created an test case you can try here: https://github.com/matthewchan15/ideo-test-case/tree/issue-annotations-multi (Render Issue Single).

Below is a GIF displaying the issue more clearly. I found that if you change the `style` of `_ideogramToolTip` to `position : fixed` with the developer tools, this becomes fixed. I have not tried modifying the source code, but I'm assuming it is as simple as changing the `position` of `_ideogramToolTip`. I could make a PR if you like!

![ideogram-annot](https://user-images.githubusercontent.com/33464965/48684825-c80d9d00-eb70-11e8-8484-756e78e20462.gif)

**Comment by eweitz** [comment]
Hi @matthewchan15, thanks for spotting the recently-introduced bug in annotation tooltips.  I'd certainly welcome a PR that fixes it!
