### ISSUE TITLE
Annotation tooltips appear behind ideogram when using multiple ideograms

### ISSUE THREAD

**Issue by matthewchan15** [eweitz/ideogram#116]
Hi, I am using the latest master, and have noticed an issue with the annotations. It seems that when the user hovers over an annotation on other Ideogram's besides the first one, the annotation shows up behind the ideogram. I created an test case you can try here: https://github.com/matthewchan15/ideo-test-case/tree/issue-annotations-multi

Below is a GIF displaying the issue more clearly. I found that if you add a `z-index: 100` to the style of `_ideogramToolTip`  with the developer tools, this becomes fixed. I have not tried modifying the source code, but I'm assuming you just need to add a `z-index` to `_ideogramToolTip`. I could make a PR if you like!

![ideogram-annot-hover](https://user-images.githubusercontent.com/33464965/48685161-1e2f1000-eb72-11e8-9ad1-adba394e0075.gif)

**Comment by eweitz** [comment]
Thanks for the report, @matthewchan15!  A PR to fix this bug with annotation tooltips would be appreciated.
