### ISSUE TITLE
Use custom specie

### ISSUE THREAD

**Issue by algarsi3** [eweitz/ideogram#120]
Is it possible to use this library with a custom generated genome?

**Comment by eweitz** [comment]
@algarsi3, yes, you can depict custom genomes with Ideogram.js.  For example:

- [Install Ideogram.js locally](https://github.com/eweitz/ideogram#installation)
- Copy the linked file [`example-organism.js.txt`](https://github.com/eweitz/ideogram/files/2638085/example-organism.js.txt) into `ideogram/dist/data/bands/native/`
- Rename `example-organism.js.txt` to `example-organism.js`
- Load http://localhost/ideogram/examples/vanilla/eukaryotes?org=example-organism


There you should see a custom genome -- the rice (_Oryza sativa_) genome with a custom chromosome 13 (chr12 with a longer pericentromeric region on the p-arm) that does not exist in the reference rice genome assembly.

I could see such use cases being helpful for visualizing genomes before they are deposited in biological databases, e.g. as a tool  for quality assurance.
