### ISSUE TITLE
Data offline: https://unpkg.com/ideogram@1.4.1/dist/js/ideogram.min.js

### ISSUE THREAD

**Issue by matthewchan15** [eweitz/ideogram#129]
Maybe this is temporary, the ideogram data doesn't load on the demo app page as well? -> https://eweitz.github.io/ideogram/human

**Comment by eweitz** [comment]
The examples load certain resources from [Unpkg](https://unpkg.com), a free content delivery network for NPM packages.  Sometimes that CDN takes a long time to load, and on rare occasion fails.  

That seems to be what happened in your case.  Things look OK now.  Thanks for reporting!
