### ISSUE TITLE
trackIndex in annotations?

### ISSUE THREAD

**Issue by kabdullah** [eweitz/ideogram#137]
I can’t get `trackIndex` to work when I simply use it in the `annotations` option. It only works in json files with `annnotationsPath`. Am I missing here something? Is there a trick to get it work?

**Comment by eweitz** [comment]
Hi @kabdullah.  No, you're right: trackIndex is currently only supported in raw annotations passed in via the `annotationsPath` option, and not the `annotations` option.  This is mostly just a coincidence of development; I had not considered using it as you suggest.

Is using trackIndex via `annotationsPath` a viable approach for your use case?  If not, I can look into also enabling trackIndex via the `annotations` option.

**Comment by kabdullah** [comment]
No. If it is possible, please add `trackIndex` into the `annotations` option. I have a database of mutations for different patients. With the `annotationsPath` option, I would need to create for each patient a json file, which I would like to avoid. Best would be if I could send the `trackIndex` information on the fly to the ideogram.js library.

**Comment by eweitz** [comment]
OK, thanks for providing additional context.

I will try adding support for `trackIndex` to the `annotations` option.  I'll update here by Monday.

**Comment by eweitz** [comment]
@kabdullah, I've drafted support for `trackIndex` in the `annotations` option.  Please:

* Download [ideogram-1-6-0-rc1.tar.gz](https://github.com/eweitz/ideogram/files/2915025/ideogram-1-6-0-rc1.tar.gz)
* Copy and unpack it in your web directory, e.g. `tar xzf ideogram-1-6-0-rc1.tar.gz` in a folder named "ideogram".
* Open the "Annotations, tracks" example, e.g. http://localhost/ideogram/examples/vanilla/annotations-tracks.html.

On line 37 of that annotations-tracks.html file you'll see a truncated, client-side hard-coded version of the "raw annotations" that supports `trackIndex`, which is passed in via the `annotations` option.  I imagine your data is formatted similarly.

Does that work for your use case?

If trying this as a draft NPM release you can reference in package.json would be easier than using a .tar.gz file, let me know.

**Comment by kabdullah** [comment]
Thanks @eweitz for implementing the ´trackIndex´ support for the ´annotations´ option. I don't see an example folder in the archive file you provided for download.

**Comment by eweitz** [comment]
My mistake, please try again.

**Comment by kabdullah** [comment]
Dear @eweitz. Works smoothly now. Thanks for the quick implementation.
