### ISSUE TITLE
'organism' (prop name) really means 'species' in this context...

### ISSUE THREAD

**Issue by mkcor** [eweitz/ideogram#138]
Hello @eweitz!

I was wondering if you would considering renaming prop [organism](https://github.com/eweitz/ideogram/blob/master/api.md#organism) into species, because really 'human' or 'mouse' refer to a species, not to an organism in particular...

I came across this while working on the Dash Bio version of Ideogram, which is based out of yours (for lack of a better reference: https://github.com/plotly/dash-bio/pull/201#discussion_r264371990). My intention is therefore to make [this change](https://github.com/plotly/dash-bio/pull/237/files#diff-fa974f21e1fe3fb9715a3dadcc18b05e), but I would much prefer it if the prop names were consistent across the board (echoing @Bachibouzouk's [comment](https://github.com/plotly/dash-bio/pull/237#pullrequestreview-214713734) here).

What do you think?

Thank you for your consideration,
Marianne

**Comment by eweitz** [comment]
Hi @mkcor, thanks for the thoughtful suggestion.  I am inclined to keep "organism" as the name of this configuration option.  Changing  the option name from "organism" to "species" would be a simple but large breaking change.  Also, "organism" is conventional, and flexible and regular in ways that "species" is not.  Let me explain.

Software for biology often uses "organism" like Ideogram does.  For example, [GenBank](https://www.ncbi.nlm.nih.gov/nuccore/?term=human%5BORGANISM%5D),  [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/?term=mouse%5BORGANISM%5D), and [UniProt](https://www.uniprot.org/uniprot/?query=organism%3Ahuman&sort=score) provide "organism" as a search filter.  [PDB](http://www.rcsb.org/pdb/results/results.do?tabtoshow=Current&qrid=3CAD2076) does similarly with "expression organism".  So Ideogram's usage of "organism" is conventional, or at least has several major bioinformatics services as precedents.

"Organism" is also flexible.  It does not entail a specific taxonomic rank, as "species" does.  Accepting `species: "mouse"` could be considered technically incorrect as "[mouse](https://en.wikipedia.org/wiki/Mouse)" is not taxonomically specific for the species _Mus musculus_.  Ideogram's "organism" option also accepts values that are more specific than species, e.g. the sub-species strain identifier "[Plasmodium falciparum 3D7](https://eweitz.github.io/ideogram/eukaryotes?org=plasmodium-falciparum-3d7)".  "Taxon" would be more ontological precise, but less accessible.  Scientists and engineers routinely say "organism" when they mean "species" when they mean "taxon", but the first is clear enough and most widely understood.

Finally, "organism" is simpler and more regular in a linguistic sense.  The plural of "organism" is "organisms".  The [plural of "species"](https://english.stackexchange.com/questions/120068/how-can-i-distinguish-between-the-singular-and-plural-of-species) is "species" -- quite irregular!  Possessive forms of the word "organism" are also simpler.  Grammatical confusion over the word "species" happens all the time, and would likely increase with the proposed rename.

All that said, ontologically, you're correct that this option usually refers to a species like "human", and not a particular instance of such a species like, say, "Carl Linnaeus".  I just think renaming it "species" would swap one set of problems for another set that is arguably worse, as described above.  This unclear overall benefit and the fact that it would be a breaking change make me prefer keeping the option named "organism".

I have [updated](https://github.com/eweitz/ideogram/commit/437a9c5b2a5dd16125a4ccc885fa537e47455dd9) the documentation for `organism`.  Hopefully that clarifies it a bit!

**Comment by mkcor** [comment]
Hi @eweitz,

Thank you very much for the prompt and detailed reply!

I don't have a bioinformatics background, so I'm more than happy to learn about these terminology conventions and precedents. I appreciate all the references backing up your arguments.

> Scientists and engineers routinely say "organism" when they mean "species" when they mean "taxon"

Just to confirm, is the missing word 'or': "Scientists and engineers routinely say "organism" when they mean "species" *or* when they mean "taxon"?

Thank you for your [update](https://github.com/eweitz/ideogram/commit/437a9c5b2a5dd16125a4ccc885fa537e47455dd9), I think it clears away any ambiguity about the use of 'organism'!

Best,
Marianne

**Comment by eweitz** [comment]
That's a valid reading, I'd say.  Cheers, and thanks to you and others at Plotly for your great integration of Ideogram!
