### ISSUE TITLE
Change annotation info displayed

### ISSUE THREAD

**Issue by kokyriakidis** [eweitz/ideogram#163]
Hi! How can I change the annotation info when I hover or click on an annotation shape (triangle etc). I would like it to show more things instead of Gene name and position.

**Comment by eweitz** [comment]
Use [`onWillShowAnnotTooltip`](https://github.com/eweitz/ideogram/blob/be768fbcbf1510ce83de36b3c2dc84ef644b2c0b/api.md#onwillshowannottooltip) to change `annot.displayName`.  

See the example in [Annotations, external data](https://eweitz.github.io/ideogram/annotations-external-data).  Relevant [source](https://github.com/eweitz/ideogram/blob/538e333e5b07d9b7ed2fad7eb5ab68bd1d557d7d/annotations-external-data.html#L140):

```
  function hyperlinkGene(annot) {
    var term = '(' + annot.name + '[gene])+AND+(Homo+sapiens[orgn])';
    var url = 'https://ncbi.nlm.nih.gov/gene/?term=' + term;
    annot.displayName =
      '<a target="_blank" href="' + url + '">' + annot.name + '</a>';
    return annot
  }
  var d3 = Ideogram.d3;
  var config = {
    organism: 'human',
    orientation: 'vertical',
    resolution: 550,
    chrHeight: 300,
    annotationHeight: 4,
    onLoad: getAndDrawAcmgGenes,
    onWillShowAnnotTooltip: hyperlinkGene
  };
```

If more would help, let me know!

**Comment by kokyriakidis** [comment]
Hi! Thank you for your reply. Because I am not so familiar with code, is there any way to use as external data variants from a vcf? I want to show each variant from a vcf file with this report

**Comment by eweitz** [comment]
Ideogram has no direct support for VCF, but if you convert your VCF file to a BED file then you could depict the BED contents as shown in the [Annotations, file URL](http://localhost:8080/examples/vanilla/annotations-file-url?asm=GRCh37&annotsUrl=https://raw.githubusercontent.com/NCBI-Hackathons/Scan2CNV/master/files/201113910010_R08C02.PennCnvOut.bed) example.

Alternatively, if you could elaborate on what in a VCF file you'd like to see depicted in Ideogram, that might help shape direct handling of VCFs in Ideogram.

**Comment by kokyriakidis** [comment]
I want to depict variants, produced from a certain interval file in the
regions I want, from a vcf file with the ideograms. The best solution is to
use as input the bed file with the regions I want and with a script to look
out in the vcf for variants in these positions and plot them in ideograms.
This could be HUGE. I would like to have the ability to hyperlink them to
the PharmGKB database when I move the mouse over AND if possible have
hyperlinked legend.  I can think of many improments but these are the most
important. I do not know if they can be implemented

Στις Πέμ, 8 Αυγ 2019 στις 2:00 μμ ο χρήστης Eric Weitz <
notifications@github.com> έγραψε:

**Comment by kokyriakidis** [comment]
I want to know if I can add more columns in the bed file and show this
information in the legend

Στις Πέμ, 8 Αυγ 2019 στις 2:23 μμ ο χρήστης Konstantinos Kyriakidis <
kokyriakidis@gmail.com> έγραψε:

**Comment by eweitz** [comment]
> I want to know if I can add more columns in the bed file and show this information in the legend

No, not trivially, after reviewing [`bed-parser.js`](https://github.com/eweitz/ideogram/blob/be768fbcbf1510ce83de36b3c2dc84ef644b2c0b/src/js/parsers/bed-parser.js).

> The best solution is to use as input the bed file with the regions I want and with a script to look out in the vcf for variants in these positions and plot them in ideograms.  This could be HUGE.

How huge, roughly?

> I would like to have the ability to hyperlink them to the PharmGKB database when I move the mouse over AND if possible have hyperlinked legend.

If you could provide a small file with example data, that would help.

**Comment by eweitz** [comment]
I think the original question has been answered.  A new GitHub issue would be best for any desired follow-up on the later discussion topics.
