### ISSUE TITLE
Uploading a Bed file instead of a URL link

### ISSUE THREAD

**Issue by GenomicsGeorge** [eweitz/ideogram#170]
This is a brilliant tool. Thank you.

I was wondering if there is a way to upload the data as a bed file rather than URL link?

That will be really helpful if it is possible.

Many thanks
George

**Comment by eweitz** [comment]
Hi George, not yet, but that's a good idea and seems technically feasible.

The [Annotations, file URL](https://eweitz.github.io/ideogram/annotations-file-url) example is the closest thing to what you're looking for.  But as you note, Ideogram currently can't display data from a BED file without having a URL to it.

That said, Ideogram might be able to read a BED file  _without uploading it_, using the File Reader API supported by modern web browsers ([docs](https://developer.mozilla.org/en-US/docs/Web/API/FileReader), [demo](https://codepen.io/matt-west/full/KjEHg)).

Here's what the user experience would look like:
* Go to a page like [Annotations, file URL](https://eweitz.github.io/ideogram/annotations-file-url)
* Click a "Load BED file" button
* Select a BED file from local computer
* See the BED data displayed in Ideogram, like [here](https://eweitz.github.io/ideogram/annotations-file-url?asm=GRCh37&annotsUrl=https://raw.githubusercontent.com/NCBI-Hackathons/Scan2CNV/master/files/201113910010_R08C02.PennCnvOut.bed), but:
  * Without ever uploading the file to a server
  * Without needing a URL to the file

Does that sound like what you're looking for? 

If so, I agree that would be really helpful.  More specifically, assuming the user already has the BED file on their computer, simply reading and displaying it from the their local file system would be drastically faster and less complicated than requiring them to upload the file, get a URL for it, and provide that to Ideogram.

**Comment by GenomicsGeorge** [comment]
Hi Eric,

Thank you for your comments.
One of my programmers colleagues created a URL link for a test bed file with the basic chr, start and end (as it is for copy number variants). However, when we uploaded the link, it came back with no marking on the ideogram. Any suggestions?

Thanks,
George

**Comment by eweitz** [comment]
I would debug with Chrome DevTools -- there is likely a JavaScript or network error being logged to the DevTools console.  That would give hints on how to proceed.

If you could attach the test BED file here (or email it to me), I'd be happy to investigate.

**Comment by GenomicsGeorge** [comment]
Thanks for your input Eric. We tried your suggestion about the genome build and it works well now

Thanks,
George

**Comment by eweitz** [comment]
I'm glad that worked!

**Comment by GenomicsGeorge** [comment]
Hi Eric,

Using your brilliant tool, I displayed my CNVs very nicely and I am using different colors for deletions and duplications. I was wondering if it is possible to display deletions /duplications at different sides of the ideogram?

Thanks,
George

**Comment by GenomicsGeorge** [comment]
For example when you are using the heatmap option or histogram option etc. As it will not work with the overlay option.

Thanks,
George

**Comment by eweitz** [comment]
Hi @GenomicsGeorge, agreed.  I aim to add support for that by March.  

You can track progress over in issue #85.
