### ISSUE TITLE
trackIndex in drawAnnots method?

### ISSUE THREAD

**Issue by helocean** [eweitz/ideogram#172]
I can’t get trackIndex to work when I simply use it in ideogram.drawAnnots method. It only works in json files with annnotationsPath. Is there a trick to get it work?
----------------------------------------------------------------------
firedebug give me a error:
TypeError: o.config.annotationTracks[n.trackIndex] is undefined
----------------------------------------------------------------------
my code is just like this:
$(results).each(function(i, result)
{
   	annots.push(
   	{
   	    name: result.name, // required
   	    chr: result.chromosome, // required
   	    start: result.chrstart, // required
   	    stop: result.chrstart, // required
   	    trackIndex: result.trackIndex
   	 });
 });

//draw annotations.
ideogram.drawAnnots(annots);

**Comment by eweitz** [comment]
@helocean, something almost like this is done in https://eweitz.github.io/ideogram/annotations-track-filters.  Exploring that example and its source might be a helpful guide.
