### ISSUE TITLE
name/info in overlay/tooltip

### ISSUE THREAD

**Issue by ejblom** [eweitz/ideogram#183]
Hi Eric
Very cool visualization. I am playing with the basic example:

`<a href="https://github.com/eweitz/ideogram/blob/gh-pages/annotations-overlaid.html" target="_blank">Source</a>
<p>Large-scale structural variations (SVs) can be depicted using colored overlays, as seen below.</p>
<script type="text/javascript">

var config = {
organism: 'human',
chrHeight: 600,
chrMargin: 5,
annotations:{"keys": [
    "chr",
    "start",
    "length",
    "color"
  ],
  "annots": [
  
    {
      "chr": "2",
      "annots": [
        [
          "nsv531656",
          11807382,
          11117382,
          "rgba(0, 0, 255, 0.55)"
        ],
        [
          "2",
          1300000,
          301000,
          "rgba(255, 0, 0, 0.65)"
        ]
      ]
    }
    
  ]
  },
 annotationsLayout: 'overlay',
orientation: 'horizontal'
 };
var ideogram = new Ideogram(config);
 </script>`

I would like to show information in the overlay, like with the very simple annotation BRCA example:

` annotations: [{
      name: 'BRCA1',
      chr: '17',
      start: 43044294,
      stop: 43125482
    }]`
where the BRCA1 info is showed in the tooltip. In the other example, the nsv531656 or 2 is not displayed. Is there a way to display this information?

Best wishes and a Merry Christmas!

EJ

**Comment by eweitz** [comment]
> Is there a way to display this information?

Hi @ejblom, no, not with that format of annotations.  

However, if you rearranged those annotations (https://eweitz.github.io/ideogram/data/annotations/10_virtual_cnvs.json) to use an array of annotation objects instead of an array of arrays, you could have the name display in the tooltip.

You'd just need to ensure the name you desire was in the `name` property, as with that BRCA1 example.

**Comment by ejblom** [comment]
Hi Eric

Thanks, that seems to work, for instance using:

annotations: [{ name: 'BRCA1', chr: '17', start: 43044294, stop: 47125482 },{ name: 'BRCA1', chr: '18', start: 43044294, stop: 47125482 }],

However, is there a way to add a color to an annotation object? Previously I used precalculated RGB values (for instance rgba(34,139,34,0.55)). Now everything is red.

Best wishes

EJ

**Comment by eweitz** [comment]
@ejblom, add a `color` property like so:

`{ name: 'BRCA1', chr: '17', start: 43044294, stop: 47125482, color: '#CCF'}`

**Comment by ejblom** [comment]
> @ejblom, add a `color` property like so:
> 
> `{ name: 'BRCA1', chr: '17', start: 43044294, stop: 47125482, color: '#CCF'}`
@eweitz 
That works excellent. Thanks a lot.
