### ISSUE TITLE
Drosophila euchromatin regions near centromere overshadowed by heterochromatin representation

### ISSUE THREAD

**Issue by rdcwuyy** [eweitz/ideogram#189]
Dear Eric,

Thanks for your fantastic work on the ideograms.

I found 3 regions (Chr2R, 3R and X) in the Drosophila ideogram misrepresented:
![Annotation 2020-01-18 125352](https://user-images.githubusercontent.com/9682240/72665181-8d65f580-39fd-11ea-8c11-e93e752f744a.png)

There might be some small issues in the source code, but a temporary solution could be to delete these three lines from ...dist/data/bands/native/drosophila-melanogaster.json:
(1) "X q pter 1 10976635 1 10976635 gpos",
(2) "2R q pter 1 4460914 1 4460914 gpos",
(3) "3R q pter 1 30597427 1 30597427 gpos", 

and we will get the following ideogram, which looks better:
![Annotation 2020-01-18 125422](https://user-images.githubusercontent.com/9682240/72665244-45939e00-39fe-11ea-9051-7a46c923906e.png)

Thanks and best regards,
Yanying

**Comment by eweitz** [comment]
Thank you for the fix, @rdcwuyy!  I implemented it in #190.

Ideogram gets its Drosophila banding data from NCBI Assembly.  When I have more time, I plan to review the data issue more closely and report it to NCBI.

Also, since you gave rather precise and correct instructions for the fix, I'd like to add you to the [authors list](https://github.com/eweitz/ideogram/blob/master/AUTHORS).  If you'd like to be included, please reply here with your name and email.

**Comment by rdcwuyy** [comment]
> Thank you for the fix, @rdcwuyy! I implemented it in #190.
> 
> Ideogram gets its Drosophila banding data from NCBI Assembly. When I have more time, I plan to review the data issue more closely and report it to NCBI.
> 
> Also, since you gave rather precise and correct instructions for the fix, I'd like to add you to the [authors list](https://github.com/eweitz/ideogram/blob/master/AUTHORS). If you'd like to be included, please reply here with your name and email.

Hi Eric,

Thanks for your kindness. It's my great honour to be on the author list, although I've done too little to be a genuine one. ;)

Anyway, my name is Yanying Wu and my email is yanying.wu@gmail.com

Cheers,
Yanying

**Comment by eweitz** [comment]
[Added](https://github.com/eweitz/ideogram/commit/d5a5402ed311ef6d3b85969c05be3db17c2bbb1e), cheers!
