### ISSUE TITLE
Horizontal chromosome size and brush

### ISSUE THREAD

**Issue by MarilyneSummo** [eweitz/ideogram#222]
Hi,

First of all thank you for this really useful library.

I use the library to view annotations on the rice genome. I have a first global view with all the chromosomes displayed vertically. Then when I click on one of the chromosomes I display a second container with the chromosomes in horizontal mode and with the brush.

My problem is that with my data the displayed chromosome is bigger than the size passed in parameter (chrHeigth 900). And therefore, the brush is blocked and cannot go to the end of the chromosome.

![bug_ideogram_geloc](https://user-images.githubusercontent.com/7238481/90408728-82b13300-e0a8-11ea-8457-3139feb504dd.gif)

My json file was generated from the convert_band_data.py script.

`{"chrBands": ["1 p 1 0 3859.4046168139284 0 16700000", "1 q 1 0 6140.595383186072 16700000 43270923", "2 p 1 0 3142.988190938289 0 13600000", "2 q 1 0 5162.184777061492 13600000 35937250", "3 p 1 0 4483.380213544324 0 19400000", "3 q 1 0 3931.9288382177565 19400000 36413819", "4 p 1 0 2241.690106772162 0 9700000", "4 q 1 0 5963.056068852518 9700000 35502694", "5 p 1 0 2865.6657035025573 0 12400000", "5 q 1 0 4057.790493630099 12400000 29958434", "6 p 1 0 3535.861714805575 0 15300000", "6 q 1 0 3685.7977353522133 15300000 31248787", "7 p 1 0 2796.335081643625 0 12100000", "7 q 1 0 4066.8466905593855 12100000 29697621", "8 p 1 0 2981.216739934112 0 12900000", "8 q 1 0 3592.0246027569137 12900000 28443022", "9 p 1 0 647.0858040167066 0 2800000", "9 q 1 0 4671.20149020163 2800000 23012720", "10 p 1 0 1895.0369974774978 0 8200000", "10 q 1 0 3468.215133751596 8200000 23207287", "11 p 1 0 277.3224874357314 0 1200000", "11 q 1 0 6429.515265944292 1200000 29021106", "12 p 1 0 2750.114667071003 0 11900000", "12 q 1 0 3612.554324297635 11900000 27531856"]}`

Is there a problem with my data ? 

I modified the example "brush" with my data to show you what is happening

![bug_ideogram](https://user-images.githubusercontent.com/7238481/90407330-aecbb480-e0a6-11ea-9a9e-f287d59060b4.gif)

**Comment by eweitz** [comment]
Hi Marilyne, awesome use case!  Thanks for the comprehensive information.

Yes, there is a problem with your data.  If you compare the cytoband JSON you posted to that in [`/dist/data/bands/native/oryza-sativa.json`](https://raw.githubusercontent.com/eweitz/ideogram/ecd2a846ee22c6b4ea7151b636c4aca7c608aab6/data/bands/native/oryza-sativa.json), you'll see yours lacks "acen" bands.  If you wish to show centromeres, then the cytoband file should have four bands per chromosome, e.g.:

```
"1 p p1 1 15617197 1 15617197 gpos50",
"1 p p1 15617197 17000000 15617197 17000000 acen",
"1 q q1 17000000 18051616 17000000 18051616 acen",
"1 q q1 18051616 43270923 18051616 43270923 gpos50",
...
```

The problem in your data is that it is effectively like:

```
"1 p p1 1 15617197 1 17000000 gpos50",
"1 q q1 17000000 43270923 18051616 43270923 gpos50",
...
```

To fix this, add placeholder acen bands in your data.  Your genome assembly seems custom, but you can use `/dist/data/bands/native/oryza-sativa.json` as a guide.  The coordinates in that file correspond to IRGSP-1.0 ([GCA_001433935.1](https://www.ncbi.nlm.nih.gov/assembly/GCA_001433935.1/)).


Let me know how that works!

Also, could you tell me more about your use case?  Is there an application or publication where I can explore it?

**Comment by MarilyneSummo** [comment]
Thank you so much for your prompt response, everything is working fine now !

This work is part of a thesis on the study of the Leucine-Rich Repeat Receptor-Like Kinase (LRR-RLK) gene family in rice genome. I use ideogram to display and browse gene annotations along the genome.
I'm also working on another project using ideogram to visualise genetic mosaicism on banana genomes.
These works are not yet published but we are working to do so in the coming months, I will send you a link as soon as the applications are accessible.

**Comment by eweitz** [comment]
Exciting stuff -- I can be reached at eric.m.weitz@gmail.com whenever they're ready.
