### ISSUE TITLE
Tooltip modification for user-defined string or hyperlink

### ISSUE THREAD

**Issue by cmixon** [eweitz/ideogram#237]
The current tooltip visible in annotations-external-data.html shows gene name (with link to NCBI) and chromosome coordinates.

Could it be modified to also show a user-defined string or a link to another URL or a local file with additional information?

This modification would be useful to display technical information about the gene, such as clinical test names (user-defined string) and data sheets (link to local file or vendor's website).

**Comment by eweitz** [comment]
Hi @cmixon, excellent use case.  This is done in the "[Related genes](https://eweitz.github.io/ideogram/related-genes?q=RAD51)" example via `annotDescriptions` in a [tailored kit](https://github.com/eweitz/ideogram/blob/master/src/js/kit/related-genes.js) module.  If you hover over a purple annotation there, you'll see links to associated interaction paths -- i.e. data beyond the annotation gene and coordinates.

Given your interest in reusing that functionality, I'll generalize it in the next two weeks or so, and integrate something like `annotDescriptions` into another live example.  I will post updates here.

**Comment by eweitz** [comment]
I just updated [Annotations, external data](https://eweitz.github.io/ideogram/annotations-external-data) with an example showing how to modify tooltips to contain user-defined strings and links.  See PR #254 for a screenshot, and specific changes needed.

Apologies for the delay on that, @cmixon.  Let me know if more would help!
