### ISSUE TITLE
Mus musculus taxonomy id (10090) fails

### ISSUE THREAD

**Issue by bioinsilico** [eweitz/ideogram#250]
Some taxonomy ids fail e.g.

new Ideogram({organism: 10090}); 

Some method requests a non-existent file https://cdn.jsdelivr.net/npm/ideogram@1.27.0/dist/data/bands/native/house-mouse.json

**Comment by eweitz** [comment]
Thanks for reporting the bug.  As a workaround, does passing the scientific name work for you?  E.g.:

`new Ideogram({organism: 'Mus musculus'});`

**Comment by bioinsilico** [comment]
Thank you @eweitz.  Yes, it works using the NCBI scientific name.

**Comment by eweitz** [comment]
Great -- glad it works for you!
