### ISSUE TITLE
Annotating genes in human pseudoautosomal regions

### ISSUE THREAD

**Issue by cmixon** [eweitz/ideogram#257]
Annotations are not drawn for genes in the pseudoautosomal regions of X and Y chromosomes because ENTREZ returns the X and Y chromosome loci for these genes.  See for example _CRLF2_ and _SHOX_.

I can map the genes to the X chromosome by changing the property value:

                                   if(result.chromosome === "X, Y"){result.chromosome = "X"};

but it would be more desirable to show these genes on both chromosomes.

**Comment by eweitz** [comment]
Agreed, it makes sense to show multiple annotations for genes with multiple loci.

So you could perhaps account for _CRLF2_ and other genes in PAR with something like:

```
// Annotation on the other sex chromosome's PAR
let otherParResult = null;

if (result.chromosome === "X, Y") {
  result.chromosome = "X"
  otherParResult = result
  otherParResult.chromosome = "Y"
};

processedResults.push(result)

if (otherParAnnot) processedResults.push(otherParResult)
```

P.S.:  Thank you for properly styling -- I had forgotten that [gene symbols ought to be italicized](https://www.biosciencewriters.com/Guidelines-for-Formatting-Gene-and-Protein-Names.aspx)!

P.P.S.: You might also be interested in https://eweitz.github.io/ideogram/homology-basic, which illustrates human PARs.

**Comment by eweitz** [comment]
Per email, it sounds like you found a solution.
