### ISSUE TITLE
Possible to change fill color of chromosome with bands off?

### ISSUE THREAD

**Issue by harijay** [eweitz/ideogram#278]
Hi , Thank you for an excellent program to generate ideograms. I really like the API and how customizable everything is. I was wondering how to change the color of the fill for the chromosomes with the bands turned off?

Is there a way to change the fill color of the chromosome?

Thanks again for an awesome program
Hari

**Comment by eweitz** [comment]
Hi @harijay, this isn't supported, but seems easy to implement.  I'll develop towards this and update you within a few days.

**Comment by harijay** [comment]
Thank you so much. That sounds great...I am a javascript and css newbie, but I will try to see if I can help in any way.

**Comment by eweitz** [comment]
@harijay, I just finished a first pass at supporting custom chromosome colors, over in #280.  What do you think?

**Comment by harijay** [comment]
This is awesome. Thank you so much for adding the feature. It looks great and just saw the merge..once the cdn js version updated will try it out with my test case.

**Comment by harijay** [comment]
Thanks a ton! I was able to webpack the library from the commit and use it to create this 
Looks great!

![image](https://user-images.githubusercontent.com/11098/130102303-b2c1c67e-4f8e-46ce-a13b-06fa923eaaad.png)

**Comment by eweitz** [comment]
Great!  Would you mind if I asked where you're using Ideogram, @harijay?  Knowing such things helps maintainability.
