### ISSUE TITLE
legend name misplaced with row name

### ISSUE THREAD

**Issue by rdcwuyy** [eweitz/ideogram#283]
Dear Eric,

Thanks for this great tool ideogram.js again.

Could you please take a look at a small issue regarding the legend labels?
The legend name seems to be misplaced as the label for the first row, and therefore the last row is missing its icon.

Here is a picture of a legend:
<img width="200" alt="Screenshot 2021-09-11 at 22 02 03" src="https://user-images.githubusercontent.com/9682240/132962006-5f933958-39d9-4c36-ba7b-e558c5a9152e.png">

And here is the source for that legend:

    var legend = [{
      name: 'Clinical significance (simulated)',
      rows: [
        {name: 'Pathogenic', color: '#F00', shape: shape},
        {name: 'Uncertain significance', color: '#CCC', shape: shape},
        {name: 'Benign', color: '#8D4', shape: shape}
      ]
    }];

Thanks and best regards,
Yanying

**Comment by eweitz** [comment]
Greetings!  This is fixed via #287.  

I aim to release an update including this fix in a week or so.  If you need it beforehand, you can [build from source](https://github.com/eweitz/ideogram/issues/89#issuecomment-360983819).

**Comment by eweitz** [comment]
This fix has been released with [Ideogram 1.32.0](https://github.com/eweitz/ideogram/releases/tag/v1.32.0).  Thanks again for reporting the issue!

**Comment by rdcwuyy** [comment]
Great! Thank you so much!

Best wishes,
Yanying
