### ISSUE TITLE
Karyotype file of dual comparison error

### ISSUE THREAD

**Issue by Hannah1746** [eweitz/ideogram#325]
Hello.

I am trying to run:

require(RIdeogram)
library(devtools)

karyotype <- read.table('karyotype.txt', header = T)
synteny <- read.table('synteny.txt', header = T)

ideogram(karyotype = karyotype, synteny = synteny)

My files look like:
karyotype.txt
Chr	Start	End	fill	species	size	color
Myx_Chr22	1	47849308	139b08	B	9.5	139b08
Myx_Chr43	1	38023304	139b08	B	9.5	139b08
Myx_Chr27	1	46332826	078dd8	A	9.5	078dd8
Myx_Chr42	1	38410338	078dd8	A	9.5	078dd8

synteny.txt
Chr1  start1	end1	Chr2	start2	end2
22	14531668	14595454	27	32941637	32994325
22	14811096	15022136	27	32437958	32709008
22	15667970	15705569	27	31616867	31646678
...

When I run this code I get this error:

Error in `[<-.data.frame`(`*tmp*`, i, 8, value = c(B = NA_real_)) : 
  new columns would leave holes after existing columns

I am just trying to understand what is going on. 

Thank you for your time.

**Comment by eweitz** [comment]
Greetings!  This repository is for Ideogram.js, a JavaScript library for chromosome visualization.  Given your helpful example code, it seems you might be looking for [RIdeogram](https://github.com/TickingClock1992/RIdeogram).

That said, if the Ideogram.js synteny examples in the following are of interest to you, let me know!
* [Genome alignment](https://eweitz.github.io/ideogram/genome-alignment)
* [Orthologs](https://eweitz.github.io/ideogram/orthologs)
* [Homology, basic](https://eweitz.github.io/ideogram/homology-basic)

[ideogRam](https://github.com/freestatman/ideogRam), the R wrapper for Ideogram.js, may well support those too.

**Comment by Hannah1746** [comment]
Thank you for your fast response. I will reach out to RIdeogram about my error. I think I could also use the Genome alignment to get that same kind of figure I am looking for. Is there example code that I could use try this out?

**Comment by eweitz** [comment]
Yup!  Source code for the [genome alignment example](https://eweitz.github.io/ideogram/genome-alignment) is available at:

https://github.com/eweitz/ideogram/blob/gh-pages/genome-alignment.html

If you'd like, I can look into making a related visualization with your data.  I'd just need your karyotype and synteny data attached or pasted in a comment here.
