### ISSUE TITLE
Chromosome disappears after being clicked for some organisms

### ISSUE THREAD

**Issue by matthewwiese** [eweitz/ideogram#330]
I first noticed this when setting my `organism` to [cassava](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=3983); however, it is also observable in grape and green algae in the [eukaryotes example](https://eweitz.github.io/ideogram/eukaryotes). A demo gif:

![ideogram](https://user-images.githubusercontent.com/2100771/206776198-b2c7e017-4857-4df3-8ea4-9b652b261072.gif)

**Comment by eweitz** [comment]
Thanks for the clear steps to reproduce.  This is a bug in handling genomes fetched directly from NCBI.

In addition to fixing this bug, I might also inline several genomes to improve load times.  So specifying cassava or _Manihot esculenta_ would automatically load the latest major genome assembly, M.esculenta_v8 (GCF_001659605.2).

Do you work with any other organisms where that would help?  Also, would you mind if I asked in which organization you're using Ideogram.js?

**Comment by eweitz** [comment]
[Fixed](#331), thanks again for the report.  Any insight on where you're using this would help Ideogram!

**Comment by matthewwiese** [comment]
Thanks so much for addressing this so quickly @eweitz!

I'm in [Dr. Edward Bucker](https://cals.cornell.edu/edward-s-buckler)'s lab at Cornell University. We haven't actually used Ideogram.js for anything yet - I've been looking into libraries that could be used inside Jupyter Notebooks to visualize chromosomes (which prompted #329). The interactivity afforded by a solution like Ideogram.js is particularly appealing.
