### ISSUE TITLE
Missing regions in fly ideogram?

### ISSUE THREAD

**Issue by nmorozovamathbio** [eweitz/ideogram#347]
Hi Eric,

I have a question about fly genome (D. melanogaster) ideograms. 

It looks like that chromosomes on ideograms have different length than in the NCBI assembly:

They look like that in Jupyter implementation  2R < X < 2L < 3L < 3R: 
![Screenshot 2023-04-21 at 13 58 13](https://user-images.githubusercontent.com/131281495/233630061-de8d22af-de47-4940-9c71-7f889b8b9224.png)

However, the lengths in the assembly are 2L < X < 2R < 3L < 3R
![Screenshot 2023-04-21 at 14 04 12](https://user-images.githubusercontent.com/131281495/233631800-807c671b-1005-435d-9096-8f8f7aa34c0c.png)

Moreover, some regions are not annotated when I try to annotate them on chromosomes, for example : 

no mark for reg1 = {'name': 'reg1', 'chr': '2R', 'start': 4314169, 'stop': 4321055}

![Screenshot 2023-04-21 at 15 26 20](https://user-images.githubusercontent.com/131281495/233648789-a53199ae-ff3a-486b-b76b-33f2d5da4f12.png)

mark appears for the same coordinates for chr2L  reg2 = {'name': 'reg2', 'chr': '2L', 'start': 4314169, 'stop': 4321055} :

![Screenshot 2023-04-21 at 15 28 44](https://user-images.githubusercontent.com/131281495/233648127-8adde589-5d98-4fb8-8b25-9a0dd25c6ac9.png)

Could it be that some regions are missing?

Natalia

**Comment by eweitz** [comment]
Hi Natalia, thanks for bringing this to my attention.  It seems at least partly caused by an issue in the underlying data, like #189.  I aim to fix this in the next release.

**Comment by daggoo** [comment]
Thanks a lot!

**Comment by eweitz** [comment]
This is resolved per #348, and the fix will be available in the next Ideogram.js release.  Thanks again for the report!

**Comment by daggoo** [comment]
Thanks again!
