### ISSUE TITLE
Annotations based on coordinate

### ISSUE THREAD

**Issue by apallav** [eweitz/ideogram#36]
Hi,

Excellent plugin. Thanks for developing and sharing it over the github. 

I am wondering if I can annotate based on chromosome coordinate so the arrow is placed exactly at that point on the ideogram.

thanks,

Aparna

**Comment by eweitz** [comment]
> annotate based on chromosome coordinate so the arrow is placed exactly at that point on the ideogram.

Yes, http://eweitz.github.io/ideogram/annotations_basic.html is probably the closest example demonstrating how to do that.  View source on that page to get the entire idea, but in brief your ideogram configuration would look something like:

```
var config = {
  org: "human",
  chrHeight: 500,
  annotationsPath: "/path/to/your/annotations.json"
};

var ideogram = new Ideogram(config);
```

If you want to display the location of [BRCA1](http://www.ncbi.nlm.nih.gov/gene/672) on chromosome 17, then `annotations.json` would contain:

```
{
  "keys": ["name", "start", "length"], 
  "annots": [{"chr": "17", "annots": [["BRCA1", 43044295, 81188]]}]
}
```

**Comment by eweitz** [comment]
Resolving, as this has been addressed for some time.
