### ISSUE TITLE
Help with Uploading a Bed file instead of a URL link

### ISSUE THREAD

**Issue by EWSBDI27** [eweitz/ideogram#369]
I want to create an Ideogram for my CNV data and I came across "https://eweitz.github.io/ideogram/annotations-file-url”. It is a great tool, however the problem here I am enchanting right now is to upload the bed file. Is there any way to upload my bed file from my local computer? If not, could you please let me know how I should create a link for my bed file?

**Comment by eweitz** [comment]
Hi Sayantani, there's no trivial way to upload a local BED file via https://eweitz.github.io/ideogram/annotations-file-url.

However, if you have an HTTP server, or cloud bucket storage (e.g. Google Cloud Storage, Amazon S3), or public data you'd be fine hosting on GitHub, then you can create a link for your file by simply copying its URL at that destination (i.e., that server, bucket, or GitHub repo file path).

For example, the link titled "Example" on that page has this URL:

* https://eweitz.github.io/ideogram/annotations-file-url?asm=GRCh37&annotsUrl=https://raw.githubusercontent.com/NCBI-Hackathons/Scan2CNV/master/files/201113910010_R08C02.PennCnvOut.bed

The "annotsUrl" encodes the location, i.e.:

* https://raw.githubusercontent.com/NCBI-Hackathons/Scan2CNV/master/files/201113910010_R08C02.PennCnvOut.bed

The GitHub file path URL for that location is:

* https://github.com/NCBI-Hackathons/Scan2CNV/blob/master/files/201113910010_R08C02.PennCnvOut.bed

You can see above how getting that `raw.githubusercontent.com` URL from the `github.com` URL is simply a matter of swapping the domain name (https://raw.githubusercontent.com -> https://github.com) and omitting the "blob/" URL segment.  Then you can paste the resulting URL right into "Example URL" input in that Ideogram page, and see your BED file visualized on the genome.

Does that help?

**Comment by EWSBDI27** [comment]
Hey Eric,

Thank you for the detailed information. I have uploaded my file on Github, however I am not quite sure how to go about removing the "blob/“ from my link. 

Here is the link to the file : https://github.com/EWSBDI27/CNV/blob/main/Book4.bed

Could you please let me know how should I proceed from this?

Thank you once again for your message. I look forward to hearing from you.

Best regards,
Sayantani

**Comment by EWSBDI27** [comment]
Hey Eric,

Thanks for your email and letting me know. My bed file is according to GRCh37. I am not quite sure why the genomic co ordinates are showing out of the range when using GRCh37. I just checked it on UCSC genome browser and it’s within the range of the chr2. 

Also, when I copied the link of my bed file which you have created and pasted it on the ideogram, I am not able to visualise anything and also not showing errors :/ 

I might be pasting the wrong URL. Could you please let me know which link I am supposed to paste? 

Best regards,
Sayantani

**Comment by eweitz** [comment]
If you:

* Go to https://eweitz.github.io/ideogram/annotations-file-url?asm=GRCh37&annotsUrl=https://raw.githubusercontent.com/EWSBDI27/CNV/main/Book4.bed
* [Open DevTools in your web browser](https://www.google.com/search?q=how+to+open+browser+devtools)
* Go to the Console panel

Then you'll see some genomic coordinates in your BED file throw an error in GRCh37:

```
Uncaught Error: Base pair out of range.  bp: 135599999; length of chr10: 135534747
```

**Comment by eweitz** [comment]
I hope that approach unblocks you!  If more would help, let me know, and we can reopen this issue.
