### ISSUE TITLE
Enable ploidy support

### ISSUE THREAD

**Issue by mrouard** [eweitz/ideogram#47]
Would it be difficult to adapt the code to propose a display for homologous chromosomes for polyploid genomes ? 

For instance, by adding a ploidy parameter in the conf file, having all chromosomes displayed.  In the case of allopolyploids, it would be nice to be able to distinguish between genome groups (e.g. A, B).

**Comment by eweitz** [comment]
Great idea, @mrouard.  If you could provide an example of which the different species you'd like to compare in an [allopolyploidy](https://en.wikipedia.org/wiki/Allopolyploidy) view, that would help me ensure I'm on the right track.

Existing examples like those in [Homology, basic](http://eweitz.github.io/ideogram/homology_basic.html) and [Homology, advanced](http://eweitz.github.io/ideogram/homology_advanced.html) are ready right now for application developers and could display sister chromatids in a diploid chromosome pair -- e.g. maternal and paternal chromosome 1.  But that basically only supports displaying one chromosome pair at a time, and I don't imagine triploidy or higher ploidy would work well.

In addition to allopolyploidy, depicting [aneuploidy](https://en.wikipedia.org/wiki/Aneuploidy) (e.g. trisomy 21) comes to mind as a use case for ploidy support in Ideogram.js.

My development plan is currently:
* Document Ideogram.js, publish to NPM
* Support coloring chromosome arms (#48, low effort) 
* Support all eukaryotes (#45, high effort)
* Support ploidy (this issue, medium effort)

**Comment by mrouard** [comment]
Thanks for your answer.
I would be glad to give you all the details and also explain how we may use Ideogram.js.
It would be easier to start by email but I could not find yours.
If you don't mind dropping a line at m.rouard@cgiar.org, I will tell you. I hope it can be of interest for your future developments too.

**Comment by mrouard** [comment]
The species would be plants such as banana, wheat or coffee where you have genomes with different letters (e.g. A, B). For instance, banana can be represented according to genome group like AA, AB, AAA, AAB etc.

**Comment by mrouard** [comment]
@eweitz just to let you know that we will take care of this feature with @zeleniy
I hope it will be compatible with your plans

**Comment by eweitz** [comment]
@mrouard, excellent!   Thanks for letting me know.  I see progress is being made in https://github.com/zeleniy/ideogram.  The [fork's issues list](https://github.com/zeleniy/ideogram/issues/5) is informative.

Ploidy support for organisms generally depends on support for eukaryotes (#45).  I'm roughly half done with that.  The plan is to keep configuration extremely simple, e.g. as in [examples/worm.html](https://github.com/eweitz/ideogram/blob/297e68a6c81cec3c2d3ab484a045288f23c7fac8/examples/worm.html):
```
var config = {
  organism: "Caenorhabditis elegans", // Scientific name for nematode worm, C. elegans
};
var ideogram = new Ideogram(config);
```

I envision the same simple configuration for plants, fungi, protozoa, and animals.  PR #54 describes the code thus far to support all eukaryotes.  Given that Ideogram can now retrieve data (a list of chromosomes) for the "best" genome of any given eukaryote using the NCBI EUtils web API, I am beginning work on rendering chromosome visualizations of that data now.

It is possible to develop support for ploidy in parallel while I develop support for all eukaryotes.  The best way I see would be to develop support for ploidy in eukaryotes that already work in Ideogram -- i.e. human and mouse.  The code for that will likely be applicable to other eukaryotes.

Feel free to ping me here or in https://github.com/zeleniy/ideogram/issues as any questions arise.  I'll update you within a week on progress for all eukaryotes.

**Comment by eweitz** [comment]
@mrouard, see [this comment in #45](https://github.com/eweitz/ideogram/issues/45#issuecomment-239995407) for an update on support for all eukaryotes.  That feature will provide a foundation for ploidy support in e.g. banana, wheat, and coffee.

**Comment by zeleniy** [comment]
Hello @eweitz. I am trying to create a native JavaScript bands description for banana (Musa acuminata). Actually i do not need bands i just want to draw chromosomes. I have a [tsv file](https://github.com/zeleniy/ideogram/files/405523/ideogram_banana_v0.1.tsv.txt) with basic data about chromosomes arms length. I wrote a simple [php script](https://github.com/zeleniy/ideogram/blob/gh-pages/scripts/convert_band_data.php) which creates .js file with native description, but it looks not very well - https://zeleniy.github.io/ideogram/examples/polyploid.html - no borders near centromere. File with data produced by PHP script [here](https://github.com/zeleniy/ideogram/blob/gh-pages/data/bands/native/ideogram_banana_v0.1.js).

Could you help me with my task? I need minimal bands description to draw chromosomes.

**Comment by eweitz** [comment]
Hi @zeleniy.   At a glance, I suspect your centromere rendering issue is caused by code around [line  933](https://github.com/zeleniy/ideogram/blob/06a841e612e03e92cbccbe5010a27d85be2005ac/src/js/ideogram.js#L933) and [line 1011](https://github.com/zeleniy/ideogram/blob/06a841e612e03e92cbccbe5010a27d85be2005ac/src/js/ideogram.js#L1011) that renders pericentromeric bands in the `drawChromosome` method.  

Please note that support for all eukaryotes (#45) will make the hard-coded chromosome data in [ideogram_banana_v0.1.tsv](https://github.com/zeleniy/ideogram/blob/69de0c0375fb95ad20de6387b6f0ff5756d33454/data/bands/ncbi/ideogram_banana_v0.1.tsv) unnecessary to render chromosomes for banana.  Feature #45 will enable app developers to draw banana's genome like so:

```
var config = {
  organism: "Musa acuminata", // Scientific name for banana
};
var ideogram = new Ideogram(config);
```

Feature #45 will not include support for rendering centromeres for any eukaryote.  So if you need to depict centromeres, then `ideogram_banana_v0.1.tsv` might still be relevant for your particular use case for at least a little while.  (To keep the tools in `scripts` consistent, `convert_band_data.php` would need to be ported from PHP to Python 3 if a goal is to merge it into this repository.)

I think your code to support polyploidy will still be useful, even when Feature #45 lands in `ideogram/master`.  I would be happy to review any pull request specifically for polyploidy support when it is ready.

**Comment by eweitz** [comment]
@mrouard, @zeleniy, support for all eukaryotes (#45) is now implemented.  That should significantly simplify configuration needed to support various ploidy renderings for any eukaryote.  

See my previous comment for an example of a generic banana (Musa acuminata) ideogram configuration.  More eukaryotes: http://eweitz.github.io/ideogram/eukaryotes.html.

**Comment by mrouard** [comment]
thank you @eweitz  for keeping us posted. We will complete the ploidy feature and will pull request soon.

**Comment by mrouard** [comment]
Hi @eweitz,

We are making progress with @zeleniy on this feature. 
You can have a look [here](https://zeleniy.github.io/ideogram/examples/polyploid.html) and [here ](https://zeleniy.github.io/ideogram/examples/rearrangements.html) 

There are still some issues to fix and a merge with current code of the your version but we hope it can be a interesting pull request for ideogram.

Please let us know if you have any suggestions or comments
Thank you

**Comment by eweitz** [comment]
@mrouard, @zeleniy, the example at https://zeleniy.github.io/ideogram/examples/polyploid.html looks like a good start in terms of UI.  Thanks for your work so far!

To merge your new feature into this repo, after fixing any regressions in existing examples, please:
* Create a new feature branch named `ploidy` in `zeleniy/ideogram`.
* Pull from [eweitz:ploidy](https://github.com/eweitz/ideogram/tree/ploidy) to get updates since your fork diverged.
* Merge.  Ensure that your copy of [eukaryotes.html](https://eweitz.github.io/ideogram/eukaryotes.html) works.
* Ensure automated test suite passes, like so:
```
$ npm -v
3.8.3
$ npm install
$ npm install gulp
$ gulp
[23:03:44] Using gulpfile /Library/WebServer/Documents/ideogram/gulpfile.js
...
18 passing (2s)
```
(Don't worry about the various warnings or seeming errors -- just get to `18 passing`.)
* Open a pull request from `zeleniy:ploidy` to `eweitz:ploidy` (not `eweitz:master`).
* Fix any issues noted in code review.

Then I will merge`zeleniy:ploidy` into `eweitz:ploidy`.  My goal is to keep the code review small-scale and relatively quick, then make any large-scale changes I propose myself.  Then I will merge the refined code into `eweitz:master`, and credit you both.

**Comment by zeleniy** [comment]
Hello @mrouard, @eweitz. I have finished with merging our changes with original master branch. Last two [examples](https://zeleniy.github.io/ideogram/examples/) demonstrate library new features:
* [Ploidy basic example/functionality](https://zeleniy.github.io/ideogram/examples/polyploid.html)
* [Ploidy extended functionality](https://zeleniy.github.io/ideogram/examples/rearrangements.html)

While developing was done two big changes:

1. Code reorganisation. All new functionality was implemented in separate classes which may be found [here](https://github.com/zeleniy/ideogram/tree/master/src/js). This is allow to minimise changes within original library. Also was written additional task for gulp with name `dist` which compile single `ideogram.min.js` file and put it into the `dist` [folder](https://github.com/zeleniy/ideogram/tree/master/dist).
2. Was changed way of chromosomes rendering. It was quite difficult to understand how it worked. So now based on `model` ideogram just render sequence of bands/rectangles and then impose [clipPath](https://developer.mozilla.org/en/docs/Web/CSS/clip-path) on that sequence like in [that example](https://jsfiddle.net/zeleniy/hhup6juq/). Code which render chromosomes stored in `views` [folder](https://github.com/zeleniy/ideogram/tree/master/src/js/views).

Unfortunately on date unit tests don't work. So if to run them you can see just set of internal errors, but all [examples](https://zeleniy.github.io/ideogram/examples/) looks very similar to original [examples](http://eweitz.github.io/ideogram/).

So @eweitz, before to do pull request i decide to discuss all the changes and know your opinion about new changes.

**Comment by eweitz** [comment]
@zeleniy, it's exciting to have this nearing completion!

Your two major changes beyond ploidy support help indicate where Ideogram.js could benefit in terms of understandability to other library developers.  The reorganization of code into finer-grained modules is a reasonable first draft.  

To digest your large upcoming pull request, I plan to address its concerns one at a time.  I see those separate concerns as follows:

* Ploidy support: enabling the feature at hand, which is demonstrated in your examples
* Code modularization: separating Ideogram.js functionality into smaller files
* Chromosome rendering: considering the `clipPath` approach

First, I would like to focus on ploidy support.  So once you open a PR from `zeleniy:ploidy` to `eweitz:ploidy`, I will ask you for some minor UI fixes, and perhaps some clarification on and documentation of the features themselves.  

Then I will address code modularization.  For this concern, I may create a new branch to make any large-scale changes I propose myself.  Then I plan to address chromosome rendering via `clipPath` and any other concerns.  Your code provides a useful starting point for that work.

I might ping you with occasional questions on those separate concerns beyond ploidy support, but I will likely address them mostly on my own.  My goal is to keep the upcoming code review small, focused and relatively quick for you.

The code in [zeleniy:ploidy](https://github.com/zeleniy/ideogram/tree/ploidy) looks ready for review.  Please open a pull request at your convenience.

**Comment by zeleniy** [comment]
Cool. I have done pull request.

**Comment by mrouard** [comment]
Hi @eweitz,

Are you considering adding new examples on the ideogram page like we did here?
https://zeleniy.github.io/ideogram/examples/

**Comment by eweitz** [comment]
@mrouard, yes, I will add the new ploidy-related examples once I finish integrating `eweitz:ploidy` into into `eweitz:master`.  That requires restoring unit tests, and I am also refining the architectural changes included in the ploidy feature work.  I am to have that public within two weeks.

**Comment by mrouard** [comment]
Thank you @eweitz. I think Ideogram is now generic for nay type of organism and could be a nice tool for an application note in some scientific journal. Is this something in your plan ?

**Comment by eweitz** [comment]
A journal publication might be feasible in 2017.  For the next few months, though, my focus will be on development.  I will let you know when I begin drafting a manuscript!

**Comment by mrouard** [comment]
I am really glad to see them there! :)

Thanks @eweitz for including our ideas and implementation in your nice library.
