### ISSUE TITLE
Arm colored

### ISSUE THREAD

**Issue by mrouard** [eweitz/ideogram#48]
Is there an option in the code to color arms of the chromosome?

**Comment by eweitz** [comment]
Not yet, @mrouard, but I've begun developing one per this issue.  An initial implementation will be ready within a few days.

**Comment by mrouard** [comment]
That's great ! thanks.

**Comment by eweitz** [comment]
@mrouard, is http://eweitz.github.io/ideogram/annotations_colored_arms.html close to what you had in mind?  The gist:

```
var config = {
  organism: "human",
  chrHeight: 500,
  armColors: ["#D00", "#CCC"] // p-arm color, q-arm color
};

var ideogram = new Ideogram(config);
```
[View source](https://github.com/eweitz/ideogram/blob/0ec06726bd34a00678932213190f78941da1ef35/annotations_colored_arms.html#L1) for full implementation details.  Let me know of any questions!
