### ISSUE TITLE
processAnnotData doesn't handle missing or unrecognized chromosomes

### ISSUE THREAD

**Issue by Lenbok** [eweitz/ideogram#66]
(I found your project yesterday, and it's quite cool!)

The parsing code in processAnnotData looks like it's stashing the reported chromosome contained in the input rawAnnots, however whatever is making use of the resulting data seems to ignore the chromosome name and just assume the annots entries are present for every chromosome in order.

For example, with the following my-test.json annotation data:

````
{"keys":["chr","start","length","color"],
 "annots":[
     {"chr":"20","annots":[["20",30954171,5816,"rgba(255, 0, 0, 0.65)"]]},
     {"chr":"foo", "annots": []},
     {"chr":"X","annots":[["X",47422351,6720,"rgba(0, 0, 255, 0.65)"]]}
 ]
}
````

And with the following configuration:
````
 var config = {
      organism: "human",
      assembly: "GRCh37",
      orientation: "vertical",
      chrMargin: 5,
      chrHeight: 200,
      annotationTracks: undefined,
      annotationsPath: "my-test.json",
      annotationsLayout: "overlay",
      dataDir: "ideogram/data/bands/native/",
  };

  var ideogram = new Ideogram(config);
````

The annotation for chromosome 20 is displayed on chromosome 1, and the annotation for chromosome X is displayed on chromosome 3. I would expect that these annotations should be displayed on the correct chromosomes. I'm not sure exactly where the problem lies.

(BTW, is there a way to display multiple ideograms in a single page? E.g. I have a set of chromosome data for several different individuals, and want to display them as separate ideograms on one page. Is it possible to add a small example to the existing examples?)

**Comment by eweitz** [comment]
Good catch!  I have a hunch on how this could be fixed (involving [sortChromosomes](https://github.com/eweitz/ideogram/blob/3addf625bf16d6722bf6907fdf0d9f1626a4fac2/src/js/core.js#L1769)), and suspect the fix can be released with the new "overlayspan" layout (#65).

I'm looking into this, and will update here this weekend.

**Comment by eweitz** [comment]
> is there a way to display multiple ideograms in a single page? .... I have a set of chromosome data for several different individuals, and want to display them as separate ideograms on one page. 

That's not supported at the moment, but it's been on my mental backlog for a while.  I'll plan to investigate that after resolving this issue and #65.  

Could you open a new issue for supporting multiple ideograms in one page, with any further details you think are relevant?

**Comment by Lenbok** [comment]
Hey cool! I see you've been busy over the weekend!! Nice stuff. I'll open that issue regarding multiple ideograms on the same page. Cheers!

**Comment by eweitz** [comment]
Thanks, I'll follow up re multiple ideograms over in #68.

This issue with `processAnnotData` has been fixed.  Details: #67.
