### ISSUE TITLE
[RFE] Ability to display multiple ideograms on one page

### ISSUE THREAD

**Issue by Lenbok** [eweitz/ideogram#68]
In some cases we might want to compare ideograms for multiple samples at once, and currently it does not seem possible. At the moment our use case is for quick comparisons of gross structural variant differences at the outer level rather than needing any zoom capability.

**Comment by eweitz** [comment]
@Lenbok, an initial implementation of this is now available, along with examples.  

Further details, screenshots in #69.  Feedback welcome!

**Comment by mrouard** [comment]
Hi @eweitz 
This is a nice addition. Would it work for the polyploid examples too?

**Comment by eweitz** [comment]
Good question, @mrouard.  

This week, I aim to wrap up some [enhancements for ploidy support](https://github.com/eweitz/ideogram/tree/enhance-ploidy) that I began before implementing Len's suggestions.  I will include an example of multiple polyploid ideograms in one page.

**Comment by mrouard** [comment]
that's good to know. Thanks!

**Comment by Lenbok** [comment]
@eweitz I got a chance to try this out yesterday, and it looks great, thanks!

**Comment by eweitz** [comment]
> an example of multiple polyploid ideograms in one page.

@mrouard, an example of that is now available at http://eweitz.github.io/ideogram/multiple_trio.html.  Details: #73.

**Comment by mrouard** [comment]
@eweitz it looks very nice! thanks.
