### ISSUE TITLE
documentation PR?

### ISSUE THREAD

**Issue by awatson1978** [eweitz/ideogram#71]
Hi,
Would you take a PR with some documentation to the readme if I submit one?  I'm up and running and would be happy to take some notes as I fine tune things, and contribute them back.

**Comment by eweitz** [comment]
@awatson1978, I am indeed open to accept pull requests, including for documentation.  

A prime goal of mine with Ideogram has been to make usage on a web page as simple as possible.  Per #70 it sounds like you're using Ideogram with Meteor and React.  Those are important web contexts, and I'm sure your notes would be helpful!

**Comment by awatson1978** [comment]
Awesome.  I'll start with documenting the config options then.  I've got a final project in my Genomics class due on the 15th; so expect something between now and then.

**Comment by eweitz** [comment]
@awatson1978, some documentation has been added to the README since we discussed this.  I am starting more detailed configuration and API documentation now.  I'll note here when that's done!

**Comment by eweitz** [comment]
See the new [Ideogram API reference](https://github.com/eweitz/ideogram/blob/master/api.md) for documentation on configuration options and methods.  Pull requests to improve that are welcome.
