### ISSUE TITLE
How is the reference data being generated?

### ISSUE THREAD

**Issue by awatson1978** [eweitz/ideogram#72]
Hi again,
So, everything is going swimmingly, and I think I've got this all sorted out so a user can upload and display their 23andMe data.  

Question:  the reference data.  How is it being generated?  I'm currently taking an Intro to Genomics class, and we've been covering `.sam`, `.bam`, `.vcf`, `.bed`, and `.fastq` files.  But I'm having a bit of trouble following what's going on in the `/data` directory.

`/data/annotations/10000_virtual_snvs.json`...  that's from the 10,000 Genomes Project, right?  Is that basically a JSON version of a `.vcf` file?

**Comment by eweitz** [comment]
> Question: the reference data. How is it being generated?

In brief, the reference data ultimately comes from the National Center for Biotechnology Information ([NCBI](https://www.ncbi.nlm.nih.gov/)).  Ideogram's dataflow scripts simply download and transform public data from NCBI.  

Further details are below, if you're interested.

The reference chromosomes fall into three categories of decreasing resolution: those with cytogenetic band data, those with centromere data, and those without centromere data.  

Also, although it is generally better to use accessioned upstream data, it is possible to see chromosomes with any of those resolutions by using draft or custom data.

## Chromosomes with cytogenetic band data
Cytogenetic band data for [human](http://eweitz.github.io/ideogram/human.html), [mouse](http://eweitz.github.io/ideogram/mouse.html) and [rat](http://eweitz.github.io/ideogram/eukaryotes.html?org=rattus-norvegicus) comes from the "Ideogram Data" tab atop the [Genome Decoration Page](https://www.ncbi.nlm.nih.gov/genome/tools/gdp/) (GDP) at NCBI, i.e. the FTP directory ftp://ftp.ncbi.nlm.nih.gov/pub/gdp/.  The Ideogram examples for those organisms use a naive JSON transformation of those TSV files from GDP.  For example, the [cytogenetic band data for human](https://github.com/eweitz/ideogram/blob/f7e40f0af2ae6ec345432727d125957b41a4097d/data/bands/native/homo-sapiens.js) in /data/bands/native is a JSON conversion of [a TSV file](https://github.com/eweitz/ideogram/blob/master/data/bands/ncbi/ideogram_9606_GCF_000001305.14_850_V1.tsv) in /data/bands/ncbi, which I copied from that upstream GDP FTP page.  The TSV-to-JSON conversion is done by [convert_band_data.py](https://github.com/eweitz/ideogram/blob/6d54c10ebfb5fddfcb1da0c57c25f151f879a73a/scripts/convert_band_data.py#L27).

Cytogenetic band data only exists for a few high-value organisms.  The remaining reference data falls into two categories: organisms that have a genome assembly with centromere data in [AGP](https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/) files, and organisms that do not.  

## Chromosomes with centromere data
For example, [chimpanzee](https://eweitz.github.io/ideogram/eukaryotes.html?org=pan-troglodytes) (_Pan troglodytes_) has centromere data.  More precisely, the chimpanzee assembly Pan_tro_3.0 ([GCF_000001515.7](https://www.ncbi.nlm.nih.gov/assembly/GCF_000001515.7)) has a row with a column labeled `centromere` in its AGP files, e.g. in `chr1.agp.gz` [here](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/515/GCF_000001515.7_Pan_tro_3.0/GCF_000001515.7_Pan_tro_3.0_assembly_structure/Primary_Assembly/assembled_chromosomes/AGP/). You can also get to those files by going to [that genome's NCBI Assembly page](https://www.ncbi.nlm.nih.gov/assembly/GCF_000001515.7) and clicking on the "Download the RefSeq assembly" link at right, then following the links indicated by the previous ("here") URL.  

Roughly [15 organisms](https://github.com/eweitz/ideogram/tree/6a25030166212cb211fc895132e940ce115af6cf/data/bands/native) have such data.  The search for, download and formatting of genome assemblies with AGPs that contain centromere data is done by [get_chromosomes.py](https://github.com/eweitz/ideogram/blob/6a25030166212cb211fc895132e940ce115af6cf/scripts/get_chromosomes.py).

## Chromosomes without centromere data
[Mosquito](https://eweitz.github.io/ideogram/eukaryotes.html?org=anopheles-gambiae) (_Anopheles gambiae_) and several hundred other organisms lack assemblies with centromere data, but do have sufficient data to be automatically supported by Ideogram.  Here again, the data comes from NCBI Assembly.  

In particular, this class of supported organism is defined by having genomes in NCBI Assembly that have an [assembly level](https://www.ncbi.nlm.nih.gov/assembly/help/#glossary) of ["Complete genome" or "Chromosome"](https://www.ncbi.nlm.nih.gov/assembly?term=%28%22complete%20genome%22%5Bfilter%5D%20OR%20%22chromosome%20level%22%5Bfilter%5D%29&cmd=DetailsSearch).  Ideogram uses NCBI's [EUtils web API](https://www.ncbi.nlm.nih.gov/books/NBK25500/) to get that data.  See the [getAssemblyAndChromosomesFromEutils](https://github.com/eweitz/ideogram/blob/b98849ac8335a5816022f5d5d909ad76f6db160d/src/js/core.js#L1850) method for implementation details, and Issue #45 for background discussion.

## Chromosomes with draft data
Finally, it is also possible to load custom chromosome reference data.  I don't think this has been tried, but I imagine it could be useful as a quality assurance step while submitting to an upstream assembly repository like [NCBI Assembly](https://www.ncbi.nlm.nih.gov/assembly/docs/submission/). This approach could be used to generate custom ideograms that show cytogenetic bands, centromeres, or simply chromosome lengths.

One would create a TSV file like [banana.tsv](https://github.com/eweitz/ideogram/blob/6a25030166212cb211fc895132e940ce115af6cf/data/bands/ncbi/banana.tsv) from one's own not-yet-accessioned data, then run [convert_band_data.py](https://github.com/eweitz/ideogram/blob/master/scripts/convert_band_data.py) to produce a file like [banana.js](https://github.com/eweitz/ideogram/blob/6a25030166212cb211fc895132e940ce115af6cf/data/bands/native/banana.js), then include that in a `<script>` element as done in the [Ploidy, rearrangement](https://eweitz.github.io/ideogram/ploidy_rearrangements.html) ([source](https://github.com/eweitz/ideogram/blob/f001db40a36d852e91ebac2dd61be8842541bafd/examples/ploidy_rearrangements.html#L9)) example.

**Comment by eweitz** [comment]
> /data/annotations/10000_virtual_snvs.json... that's from the 10,000 Genomes Project, right? Is that basically a JSON version of a .vcf file?

[That file](https://github.com/eweitz/ideogram/blob/7d94b5a3b230de68b5f51ab0154cbdb54b57a952/data/annotations/10000_virtual_snvs.json) is actually just a set of virtual, i.e. simulated, single nucleotide variations (SNVs) that are randomly distributed throughout the genome.  It's basically test data, generated by [create_annots.py](https://github.com/eweitz/ideogram/blob/ca64a3c51e1b5ecaae89d2422ffc408565743644/scripts/create_annots.py) and not pulled from any upstream data source like the 1000 Genomes Project or dbSNP.

> I think I've got this all sorted out so a user can upload and display their 23andMe data.

Very cool!  Integrating 23AndMe into Ideogram's dataflow scripts would be a great addition, if you have a PR in mind.

I've done something somewhat similar for AncestryDNA raw data in [analyze_ancestrydna.py](https://github.com/eweitz/ideogram/blob/master/scripts/analyze_ancestrydna.py). (Though please note that the ClinVar integration is not reliable, not official and basically has been for my personal experimentation.)

**Comment by awatson1978** [comment]
Hmmm....  going to have to think through this, and consult with my professor.  I may have overstated having gotten the 23andMe data completely working.  

I definitely got a `.bed` file loaded into it, and have effectively defined a genomics test panel:

![screen shot 2017-03-06 at 2 27 07 am](https://cloud.githubusercontent.com/assets/675910/23630341/66c1ee5a-0280-11e7-847e-1ee31fb7a9e7.png)

Now I need to use this to scan the 23andMe results.  Exciting stuff!

**Comment by eweitz** [comment]
Awesome!  It sounds like you are well on your way.

One thing to note: [23andMe uses GRCh37](https://customercare.23andme.com/hc/en-us/articles/202907620-Which-reference-genome-does-23andMe-use-), the previous major version of the human reference genome assembly.  However, Ideogram [defaults](https://github.com/eweitz/ideogram/blob/b98849ac8335a5816022f5d5d909ad76f6db160d/src/js/core.js#L166) to GRCh38, the current major version of the human reference genome.  [GRCh37](https://www.ncbi.nlm.nih.gov/grc/human/data?asm=GRCh37) and [GRCh38](https://www.ncbi.nlm.nih.gov/grc/human/data?asm=GRCh38) need to be distinguished because the chromosomes are of different lengths between the two versions; genomic coordinates in GRCh37 are not equivalent to those in GRCh38.

So, if you're not already doing so, you'll likely want to specify `assembly: "GRCh37"` in the Ideogram configuration, as done in e.g. [ancestry_tracks.html](https://github.com/eweitz/ideogram/blob/master/examples/ancestry_tracks.html#L30).
