### ISSUE TITLE
Cite ideogram.js

### ISSUE THREAD

**Issue by gaitat** [eweitz/ideogram#74]
How do we cite this work?

**Comment by eweitz** [comment]
@gaitat, for now please cite this work along the lines of the following:

Weitz, Eric M. Ideogram.js.  2015.  https://github.com/eweitz/ideogram.

**Comment by eweitz** [comment]
Also, @gaitat, would you mind if I asked where you are using Ideogram.js?  Concrete usage examples from other people help me prioritize where I focus development.

**Comment by eweitz** [comment]
A work related to Ideogram.js, also citable:

Weitz, Eric M.; Pantano, Lorena; Zhu, Jingzhi; Upton, Bennett; Busby, Ben.  [Viewing RNA-seq data on the entire human genome](https://f1000research.com/articles/6-596/v1). F1000Research 2017, 6:596

**Comment by gaitat** [comment]
I am not using it per se. I am reference it in a paper I am writing.
