### ISSUE TITLE
line-height css property in body tag may mess themes

### ISSUE THREAD

**Issue by pmoulos** [eweitz/ideogram#77]
Hi @eweitz ,

First of all, thanks for the magnificent work you 've done with ```ideogram.js```. Something like this was really missing.

An issue that I've just spotted (may not a real issue) is that in ```ideogram.css``` stylesheet you assign the line-height property as ```line-height: 19.6px;``` in the whole body element. This may override other styling themes (it happened in my case and created a mess with the whole application which took me some time to find out).

Is it possible that you somehow restructure the styling in upcoming versions so as to avoid this? Or if you do it for demo purposes, maybe remove it from the ideogram css stylesheet?

Thanks again for all the work.

**Comment by eweitz** [comment]
Hi @pmoulos, thanks for the kind words!

You're right that the line-height style rule was too broad.  Coincidentally, I [fixed that yesterday](https://github.com/eweitz/ideogram/commits/master?after=b701dc0b76089842d50860c8c6cf5aa6d8dec564+0) in `master`.  Ideogram no longer requires importing CSS files -- the style rules are now embedded in the SVG element.  This simplifies Ideogram setup for developers, and I have a hunch it will make export to PNG and PDF easier.  

I've [renamed](https://github.com/eweitz/ideogram/commit/a0e3f06db6a765c3efe882d1c7fed2469893a5d0) `ideogram.css` to `examples.css` and pared it down to contain only that `body` rule with the font styles in question.  Omitting that CSS link for `../src/css/examples.css` should fix the problem.  

Can you pull from `master` and let me know if the latest code fixes this bug for you?

**Comment by pmoulos** [comment]
Yes, it works out of the box now (I just removed the offending CSS before with no significant impact to the chromosome views, at least for my case). Thanks for your help!
