### ISSUE TITLE
Display assembly hg18

### ISSUE THREAD

**Issue by KyleGao** [eweitz/ideogram#81]
I am trying to have plots in hg18, and I tried a couple of values for parameter assembly:
hg18, NCBI36, GCF_000001405.12,
none of them worked.

What's the proper way of doing it?

**Comment by eweitz** [comment]
@KyleGao, I just implemented support for that old human reference genome assembly.  You can get it in the freshly-released Ideogram.js v0.11.0.

Example:
```
var ideogram = new Ideogram({
  organism: 'human',
  assembly: 'GCF_000001405.12'
});
```
