### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by jimlund** [eweitz/ideogram#89]
I'm trying to add mouseover to ideogram, and build it minimized.

After:
npm install ideogram
and 
npm install webpack

I tried to run webpack --optimize-minimize 
and get this error:

```
ERROR in ideogram.min.js from UglifyJs
Unexpected token: name (Ploidy) [./src/js/ploidy.js:1,0][ideogram.min.js:6516,6]
```

So how should this be built minimized?

Cheers,

Jim

**Comment by eweitz** [comment]
@jimlund, try:
```
git clone https://github.com/eweitz/ideogram
cd ideogram
npm install . --save-dev
# make your source code changes, then
npm run build
npm test
```

Once your mouseover is added and your build passes tests, I'd be happy to review a pull request!
